[package]
name = "list-steam-appdetails-properties"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
steam-webapi-rust-sdk = "0.0.3"
serde_json = { version="1.0.82" }
